### ISSUE TITLE
Doesn't work with Git Bash on Windows.

### ISSUE THREAD

**Issue by Alaricus** [kimmobrunfeldt/spawn-default-shell#6]
When running Git Bash on Windows (Win10 in my case) due to the fact that bash is actually bash.exe, detectExecuteFlags() doesn't have a valid return path and so an error is thrown. Specifically I encountered this issue with Angular2 QuickStart Seed. I was able to fix it by replacing 
`const DETECT_SH_REGEX = /sh$/;`
with
`const DETECT_SH_REGEX = /(sh|sh.exe)$/i;`
The `/i` is necessary too, since without it a path such as `C:\Program Files\Git\usr\bash` is not working.

Additionally, it appears that the `-l` flag breaks in Windows. So I replaced
`  if (shell.match(DETECT_CMD_REGEX)) {`
`    return '/c';`
`  } else if (shell.match(DETECT_SH_REGEX)) {`
`    return '-l -c';`
`  }`
with
`  if (shell.match(DETECT_CMD_REGEX)) {`
`    return '/c';`
`  } else if (shell.match(DETECT_SH_REGEX)) {`
`    if (process.platform === 'win32') {`
`      return '-c';`
`    } else {`
`      return '-l -c';`
`    }`
`  }`
and tested it. It works perfectly now.

Thank you! =)

P.S. — I made a pull request, but didn't touch any of your unit tests, so they are failing.

**Comment by jeevanKreddy** [comment]
After i followed above steps still i am facing the issue. The below error i got

[0] C:\Users\jereddy\AppData\Local\Programs\Git\bin\bash: C:\Users\jereddy\AppDa                                                                                                                ta\Local\Programs\Git\bin\bash: cannot execute binary file
[0] tsc -w exited with code 126
[1] C:\Users\jereddy\AppData\Local\Programs\Git\bin\bash: C:\Users\jereddy\AppDa                                                                                                                ta\Local\Programs\Git\bin\bash: cannot execute binary file
[1] lite-server exited with code 126

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jereddy\\AppData                                                                                                                \\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-ser                                                                                                                ver" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 start script 'tsc && concurrentl                                                                                                                y "tsc -w" "lite-server" '.


Changes made in JS file as below
const DETECT_SH_REGEX = /sh$/;  to
const DETECT_SH_REGEX = /(sh|sh.exe)$/i;

and the below lines

  if (shell.match(DETECT_CMD_REGEX)) {
return '/c';
} else if (shell.match(DETECT_SH_REGEX)) {
if (process.platform === 'win32') {
return '-c';
} else {
return '-l -c';
}
}

**Comment by Alaricus** [comment]
jeevanKreddy, it appears that your environment variable is pointing to the wrong instance of bash.

Instead of `C:\Users\jereddy\AppData\Local\Programs\Git\bin\bash` try something like `C:\Program Files\Git\usr\bin\bash` depending on where you installed Git.

Either way, the bash you want would be located in `\Git\usr\bin\` as opposed to `\Git\bin\`

Hope this helps.

**Comment by jeevanKreddy** [comment]
As you suggested i have modified the env variable value from \GIT\bin to  \Git\usr\bin 

i have GIT in below path C:\Users\jereddy\AppData\Local\Programs\

Still i am getting the same

 C:\Users\jereddy\AppData\Local\Programs\Git\usr\bin\bash: C:\Users\jereddy\A                                                                                                                ppData\Local\Programs\Git\usr\bin\bash: cannot execute binary file
[0] tsc -w exited with code 126
[1] C:\Users\jereddy\AppData\Local\Programs\Git\usr\bin\bash: C:\Users\jereddy\A                                                                                                                ppData\Local\Programs\Git\usr\bin\bash: cannot execute binary file
[1] lite-server exited with code 126

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jereddy\\AppData                                                                                                                \\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.4
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 start: `tsc && concurrently "tsc -w" "lite-ser                                                                                                                ver" `
npm ERR! Exit status 1

**Comment by corasla** [comment]
@Alaricus Thanks! Your fix with changing the DETECT_SH_REGEX worked like a charm. I also had to unset the SHELL env var that I previously set
